baseurl = "https://erikdesmedt.github.io/carrousel"
title = "Carrousel - Zomeravonden"
theme = "hugo-tracks-theme"
languageCode = "be-en"
canonifyUrls = true

[params]
  # Use custom.css for your custom styling
  style = "default"
  pages = false
  description = "Carrousel Zomeravonden 2019"
  copyright = "&copy;2019 Carrousel vzw"
  sidebarAbout = [
    "Muziek en gezelligheid in het parkske",
    ""
  ]



  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"

  [[params.navlinks]]
  name = "Bands"
  url = "/bands/"

  [[params.navlinks]]
  name = "Route"
  url = "/route/"

  [params.social]
  facebook      = "http://www.facebook.com/carrouselschilde"
