baseurl = "http://www.carrouselschilde.be/"
title = "Carrousel - Zomeravonden"
theme = "carrousel-announcement"
languageCode = "en-us"
canonifyUrls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Carrousel Zomeravonden"

[Author]
  name = "Carrousel VZW"
  email = "erikdesmedt@gmail.com"

[Social]
  facebook = "carrousel"