baseurl = "https://carrouselschilde.be/"
title = "Carrousel - Zomeravonden"
theme = "carrousel-announcement"
languageCode = "nl-be"
canonifyUrls = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Carrousel Zomeravonden"
  inschrijving_quiz_url = "https://forms.gle/cgXKXWmr5rXV8ADJ9"
  inschrijving_toots_url = "https://forms.gle/977nFiECiUMNDVbu9"
  inschrijving_veston_url = "https://forms.gle/W6o2a7Se9WRA43cs7"


[Author]
  name = "Carrousel VZW"
  email = "erikdesmedt@gmail.com"

[menu]
    [[menu.main]]
    identifier = "Home"
    name = "Start"
    url = "/"
    weight = 10

    [[menu.main]]
    identifier = "quiz"
    name = "Quiz"
    url = "/activiteiten/quiz/"
    weight = 20

#    [[menu.main]]
#    identifier = "concert"
#    name = "Concert Veston"
#    url = "/activiteiten/veston/"
#    weight = 30

    [[menu.main]]
    identifier = "inschrijven"
    name = "Inschrijven"
    url = "/inschrijven"
    weight = 40

    [[menu.main]]
    identifier = "locatie"
    name = "Locatie"
    url = "/locatie/"
    weight = 50



[markup.goldmark.renderer]
unsafe= true
